services:
  nginx:
    image: nginx:1.26
    container_name: nginx
    ports:
      - '80:80'
      - '8081:8081'
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    networks:
      - ingress
    depends_on:
      - kibana
  kanban-postgres:
    image: postgres:9.6-alpine
    container_name: kanban-postgres
    ports:
      - '5432:5432'
    volumes:
      - kanban-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    networks:
      - ingress
  pgAdmin:
    image: dpage/pgadmin4:5.1
    container_name: pgAdmin
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@test.com
      PGADMIN_DEFAULT_PASSWORD: kanban
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      - ingress
    depends_on:
      - kanban-postgres    
  kanban-app:
    container_name: kanban-app
    build: ./kanban-app
    ports:
      - '8080:8080'
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    links:
      - kanban-postgres
    networks:
      - ingress
  kanban-ui:
    container_name: kanban-ui
    build: ./kanban-ui
    ports:
      - '4200:80'
    links:
      - kanban-app
    networks:
      - ingress
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/etc/prometheus/
    depends_on:
      - kanban-ui
    networks:
      - ingress
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - kanban-ui
    networks:
      - ingress
  node_exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - ingress
  nginx_exporter:
    container_name: nginx_exporter
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - '9113:9113'
    depends_on:
      - nginx
    command:
      - '--nginx.scrape-uri=http://192.168.0.11:8081/metrics'
    networks:
      - ingress
  postgres_exporter:
    container_name: postgres_exporter
    image: prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - '9187:9187'
    depends_on:
      - kanban-postgres
    environment:
      DATA_SOURCE_URI: "kanban-postgres:5432/kanban?sslmode=disable"
      DATA_SOURCE_USER: "kanban"
      DATA_SOURCE_PASS: "kanban"
    networks:
      - ingress
  elasticsearch:
    container_name: elasticsearch
    image: library/elasticsearch:8.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=passwd123
      - xpack.license.self_generated.type=basic
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - ingress
    depends_on:
      - kanban-ui
  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
      - kibana
      - kanban-ui
    networks:
      - ingress
  kibana:
    container_name: kibana
    image: library/kibana:8.5.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - kanban-ui
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - PATH_DATA=/usr/share/kibana/data 
    networks:
      - ingress
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev:/dev:ro"
    privileged: true
    networks:
      - ingress
volumes:
  kanban-data:
  pgadmin-data:
  prometheus:
  grafana:
  elasticsearch_data:
  kibana_data:
networks:
  ingress:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
